### ISSUE TITLE
URLlib no longer used by Ansible?

### ISSUE THREAD

**Issue by davester14** [cyberark/ansible-security-automation-collection#11]
Cyberark_Account.py uses urllib - specifically for handling HTTP Errors;

Line 378 - 

> from ansible.module_utils.six.moves.urllib.error import HTTPError

returns the following error; "No name 'urllib' in module '_MovedItems'"

**Comment by infamousjoeg** [comment]
I believe this was an issue with Ansible that was remedied in newer versions of Ansible.  I cannot recreate this error.  Closing this, but if it is still occurring, please reopen a newer issue.
