### ISSUE TITLE
Update Galaxy collection

### ISSUE THREAD

**Issue by pint2oo** [cyberark/ansible-security-automation-collection#17]
Hi, 

Currently, cyberark_account.py does not work out of the box when downloaded from Galaxy.
The latest commit fa1c6ede4641a0e1149cbe8717b1d79bdac7d33e seems to fix those issues, but is not included in v.1.0.5 of the cyberark.pas collection on Galaxy.
Could you update the collection ?

Best, 

pint2oo

**Comment by db0** [comment]
Looks like 1.0.6 has been added which handles the new API
