### ISSUE TITLE
concurrentSessions not working

### ISSUE THREAD

**Issue by linionbb** [cyberark/ansible-security-automation-collection#34]
## Summary

There is no support currently for having multiple sessions. 
Seems to be a bug in the code:
concurrentSessions is not a valid body parameter for the API (v2).
The field name is concurrentSession (without 's').

## Steps to Reproduce

Try to use concurrentsessions in a play, does not work.

## Expected Results

Multiple sessions allowed by same user

## Actual Results

Session is logged out when another token is requested

## Reproducible

   * [*] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

v12.1

## Environment setup

* Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
VM
* Which cloud provider? Which container orchestrator (including version)? 
* The more info you can share about your runtime environment, the better we may be able to reproduce the issue.
Ansible 2.9.21

## Additional Information

*Add any other context about the problem here.*

**Comment by pint2oo** [comment]
Commit c8eed7331850a11d456ed69eb22c450f1165b25d apparently includes the fix for this.

**Comment by linionbb** [comment]
Indeed... Could be useful if cyberark closes these issues after fixing...
