### ISSUE TITLE
Please publish newest cyberark.pas collection to galaxy and update automationhub

### ISSUE THREAD

**Issue by jasondugger** [cyberark/ansible-security-automation-collection#38]
Currently Galaxy has version 1.0.7, but it doesn't support v2 api or ldap authentication as referenced in the documentation

Also, automationhub references version 1.0.5, which is old information. Please update automationhug to reference the actual galaxy version as the official release

**Comment by cbarga** [comment]
Has anyone had a chance to look into this?

**Comment by doodlesbykumbi** [comment]
Hi @cbarga. I'm currently working on this

**Comment by doodlesbykumbi** [comment]
Apologies! This issue came up on my notifications and I confused it with a similar issue that I am currently working on https://github.com/cyberark/ansible-conjur-collection/issues/56

**Comment by pint2oo** [comment]
Version 1.0.13 was just pushed. Any way we could get that on Galaxy ?

**Comment by pint2oo** [comment]
Oops, my bad, it was published :) Thanks.

**Comment by infamousjoeg** [comment]
Closing stale issue.
