### ISSUE TITLE
Collection Requirements Violation - Repository Management

### ISSUE THREAD

**Issue by gotmax23** [cyberark/ansible-security-automation-collection#46]
Hi! The Ansible Community Steering Committee has determined that this collection does not tag its releases in its git repository. This violates the [repository management](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management) section of the Collection Requirements:

> Every collection MUST have a public git repository. Releases of the collection MUST be tagged in said repository. This means that releases MUST be git `tag`ed and that the tag name MUST exactly match the Galaxy version number. Tag names MAY have a `v` prefix, but a collection's tag names MUST have a consistent format from release to release.
>
> Additionally, collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection's git repository as that release. Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

Note that this requirement has recently [been clarified](https://github.com/ansible-collections/overview/commit/6dbb5037c09dce9324cb39e322be2f42e068f117), but its intent remains the same. Please tag at least the previous 1-2 releases of your collection to come into compliance.

Please keep us updated and let us know if you have any questions. Thanks!

**Comment by gotmax23** [comment]
Has there been any progress here? This collection remains in violation of the Collection Requirements.

**Comment by felixfontein** [comment]
@cyberark-bizdev can you please take a look?

**Comment by gotmax23** [comment]
I have opened https://github.com/ansible-community/community-topics/issues/168 about removing this collection from the Ansible community package due to this unresolved Collection Requirements violation.

**Comment by jtuttle** [comment]
Hi there, I'm the manager of the CyberArk Community & Integrations team at CyberArk. We are responsible for most of the OSS repositories but unfortunately this one doesn't fall under our umbrella. This lapse has just been brought to my attention. I will try to get the appropriate person / team working on it ASAP. Sorry for the delay.

**Comment by jtuttle** [comment]
Update: I reached out to the person that manages @cyberark-bizdev directly and he said he will try to address it in the next few days, which I reckon will be next week sometime since it's Friday. I'll be on vacation next week but will try to hop on at some point to make sure this has been resolved.

**Comment by infamousjoeg** [comment]
This was fixed 5 days ago in release 1.0.14.
