### ISSUE TITLE
Authentication module adding Timeout

### ISSUE THREAD

**Issue by mrendo** [cyberark/ansible-security-automation-collection#47]
## Is your feature request related to a problem? Please describe.

We noticed now we have turned on two factor we have a problem with the module timing out before we have pressed the push notification. 

## Describe the solution you would like

Adding a timeout option to the authentication module. 

## Describe alternatives you have considered

N/A

## Additional context

I have a pull request that will fix this.

**Comment by mrendo** [comment]
Hello any update on this?

**Comment by szh** [comment]
Hi @mrendo,
Sorry for the delay. I'm going to reach out to the people responsible for this repo.
