### ISSUE TITLE
Hard coded to use AIMWebService

### ISSUE THREAD

**Issue by bab29** [cyberark/ansible-security-automation-collection#56]
Need to be able to point to alternate sites on the CCP to allow for different authentications settings. Some applications require client certificate while others are not able to leverage certificate. This connector as written forces me to install two separate CCP to support all my applications instead of just adding a second security configuration per the documentation, I have to have one CCP to require client certs and another that doesn't. 

https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-CP/Latest/en/Content/CCP/Configure_CCPWindows.htm?tocpath=Administration%7CCentral%20Credential%20Provider%7CCentral%20Credential%20Provider%20web%20service%20configuration%7C_____0#MultiplesecurityconfigurationsandauthenticationmethodsfortheCentralCredentialProviderwebservice

https://github.com/cyberark/ansible-security-automation-collection/blob/171f9d04846c82db5d39b5819200b41383a3647d/plugins/modules/cyberark_credential.py#L235

**Comment by bab29** [comment]
Request is to add api_endpoint_url which would default to "AIMWebService" but can be provide to allow it to be changed to something like "/RestCert/api/Accounts?AppId=%s&Query=%s&"

**Comment by mpieters3** [comment]
I've created a fix for this, but it doesn't look like CyberArk permits contribution:
https://github.com/mpieters3/ansible-security-automation-collection/tree/path-override-credential-retrieval

**Comment by compostCY** [comment]
I think this is a valid enhancement request  - we can consider this on the next release.
