### ISSUE TITLE
Collection Requirements Violation - Repository Management (2)

### ISSUE THREAD

**Issue by gotmax23** [cyberark/ansible-security-automation-collection#58]
Hi! As part of the ansible community package release process,
we've determined that versions 1.0.18 and 1.0.19 of cyberark.pas were released to
Ansible Galaxy but not properly tagged in this Git repository.
This violates the [repository management][1] section of the Collection Requirements:

[1]: https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#repository-management

 > Every collection MUST have a public git repository. Releases of the collection MUST be tagged in said repository. This means that releases MUST be `git tag`ed and that the tag name MUST exactly match the Galaxy version number. Tag names MAY have a `v` prefix, but a collection's tag names MUST have a consistent format from release to release.
 >
 > Additionally, collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection's git repository as that release. Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

 If the collection maintainers do not respond to this issue within a
 reasonable a amount of time,
 the collection is subject to [Removal from ansible][2].

 [2]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#collections-not-satisfying-the-collection-requirements

Note that we've already reported this issue once in https://github.com/cyberark/ansible-security-automation-collection/issues/46 and the collection is again violating this requirement.

**Comment by cyberark-bizdev** [comment]
I tagged the releases

**Comment by gotmax23** [comment]
Nope, it looks good to me. Thanks! Please make sure that tagging releases is a regular part of the release process so this doesn't happen again.
