### ISSUE TITLE
Direct galaxy.ansible.com/cyberark/bizdev to new location

### ISSUE THREAD

**Issue by gundalow** [cyberark/ansible-security-automation-collection#6]
Hi,
I see from https://galaxy.ansible.com/cyberark/bizdev that it's deprecated, though it took some hunting around to see where that content lives now.

Can you please publish an update so the README.md only has a single line which points to https://galaxy.ansible.com/cyberark/pas

**Comment by gundalow** [comment]
@cyberark-bizdev could you please take a look at this?

**Comment by infamousjoeg** [comment]
This was completed in an update to the README a while ago.  Closing the orphaned issue.
