### ISSUE TITLE
EDA plugin must be under extensions/eda/event_source

### ISSUE THREAD

**Issue by alisonlhart** [cyberark/ansible-security-automation-collection#67]
## Summary

EDA structure requires event_source and event_filter plugins to be under an `extensions/eda/event_source` or `extensions/eda/event_filter` respectively. The collection's EDA plugin is currently located under `plugins/event_source/syslog.py`. 

This should be moved to `extensions/eda/event_source/syslog.py`. See EDA docs [here](https://ansible.readthedocs.io/projects/rulebook/en/stable/sources.html#distributing-plugins) for more info. 

## Steps to Reproduce

N/A

## Expected Results

N/A

## Actual Results

N/A

## Reproducible

N/A
   
## Version/Tag number

1.0.25 collection release

## Environment setup

Collection source

## Additional Information

This may result in new failures on Automation Hub, since existing test tooling does not evaluate under the `extensions/` directory and there is a separate test process for this content. This is subject to change in the future, but currently we use the common python testing tool `tox` to perform static code analysis with a set of linters.

The linters used for EDA are: pylint, darglint, and ruff. These linters run specifically over the `<root>/extensions/eda/plugins` dir or deeper. We have built a tox template you can plug into your CI to mimic the tests on Automation Hub. We highly recommend using this template, as some of these linter tests have been deemed irrelevant for certification and are skipped. The link to the templates and documentation is here: https://github.com/ansible/eda-partner-testing

**Comment by cyberark-bizdev** [comment]
Fixed on #70
