### ISSUE TITLE
cyberark.pas 1.0.27 is not tagged

### ISSUE THREAD

**Issue by felixfontein** [cyberark/ansible-security-automation-collection#71]
## Summary

Hi! As part of the ansible community package release process, we've determined that version 1.0.27 of cyberark.pas was released to Ansible Galaxy but not properly tagged in this Git repository. This violates the [repository management](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#repository-management) section of the Collection Requirements:

> Every collection MUST have a public git repository. Releases of the collection MUST be tagged in said repository. This means that releases MUST be git taged and that the tag name MUST exactly match the Galaxy version number. Tag names MAY have a v prefix, but a collection's tag names MUST have a consistent format from release to release.
>
> Additionally, collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection's git repository as that release. Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

If the collection maintainers do not respond to this issue within a reasonable a amount of time, the collection is subject to [Removal from ansible](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#collections-not-satisfying-the-collection-requirements).

**Comment by felixfontein** [comment]
@szh @cyberark-bizdev any update on this? It's still not tagged: https://github.com/cyberark/ansible-security-automation-collection/tags

**Comment by szh** [comment]
I've ping them internally. This is managed by our bizdev department, not R&D (which I'm in), and I have very little visibility into how they work.

**Comment by felixfontein** [comment]
The 1.0.27 tag has been added in the meantime. I don't know when that happened, but not mentioning it here resulted in the constraint not being removed, and thus 1.0.27 not being included in the last Ansible release(s), even if the tag was already around by then.
