### ISSUE TITLE
LDAP authentication support

### ISSUE THREAD

**Issue by jm987** [cyberark/ansible-security-automation-collection#8]
According to the Authentication documentation, it says it supports LDAP.  I don't see an option on how to use the module while using an LDAP account.  I took at look at the Python module and only see support for Shared Auth and CyberArk Auth.   

https://github.com/cyberark/ansible-security-automation-collection/blob/master/docs/cyberark_authentication.md

**Comment by jodyhuntatx** [comment]
This issue can be closed. The library was refactored to use the PAS v2 APIs that support LDAP, Radius and Windows authentication.
